[package]
name = "nomic_status"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = { version = "1.9", features = ["serde"] }
chrono = "0.4"
tempfile = "3.3"
serde_json = "1.0"
clap = { version = "4.3", features = ["derive"] }
regex = "1.6"
