[package]
name = "columnizer"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
clap = "4"  # For command-line argument parsing
unicode-width = "0.1.13"

[[bin]]
name = "columnizer"
path = "src/main.rs"
